        // Define the paragraph text
        var paragraph = "My metaphor for a website is a drop of water in the ocean. Each drop in the ocean consists of different compositions and matter. Some have more gold, heavy metals, zinc, organic matter, viruses, and bacteria. Just like a website, it could be simple, could be complex, a scam website, or a virus website. Depending on the location, the drop in the ocean might be warmer, colder, brighter, or darker. Normal websites and dark webs are like water in shallow water and deep sea water, some are more visible, and some are mysterious and hidden. Some websites are more popular than everyone uses, and some are hidden in the dark corners that nobody knows.Each drop of water in the ocean facilitates something else, it serves as a medium for fish and sea animals to breathe oxygen. Like a website, it has its function, it could work as a platform to promote one's works, a place to share ideas, and a medium to grow a community. However, ultimately, water holds everything in the ocean together including living organisms and matter. Just like the World Wide Web, all the websites are ultimately linked together like a drop of water in the ocean is connected to all the other drops of water. It facilitates the diversity of live forms in the ocean.The quantity of drops of water in the ocean creates new systems, like circulations. Water currents generated by temperature differences are like trends online, for example, the crypto NFT metaverse trend. It creates momentum for a certain direction of water flow. Water also evaporates and consolidates or crystalizes into ice. This creates water cycles that nourish and make the ocean alive.  Website trends, designs, and functional websites change and evolve with hype cycles.Water has different forms, just like all matter. Water that is being consolidated into ice is like websites that never change but are visible to the public. It is also hard and difficult to change shape. Just like water from the North Pole, although rigid and hard to access, it stores the mass amount of historical information that is buried deep under ice. Websites that are like ice are hard-coded, not flexible, but it last a long time without maintenance. On the other hand, water that is evaporated is like highly evolving websites, they are quick to change, adaptable, and flexible. They might not last a long time but are certainly malleable and could morph into any shape. These websites could be prototype websites or MVP landing pages that change swiftly.";

        // Split the paragraph into words
        var words = paragraph.split(" ");

        // Create the table
        var table = document.getElementById("wordTable");

        // Loop through the words to populate the table
        for (var i = 0; i < words.length; i++) {
            // Create a new row for every 5 words
            if (i % 10 === 0) {
                var row = table.insertRow();
            }
            // Insert a cell into the current row
            var cell = row.insertCell();
            // Create a new paragraph element
            var paragraphElement = document.createElement("p");
            // Set the text content of the paragraph to the current word
            paragraphElement.textContent = words[i];
            // Append the paragraph to the cell
            cell.appendChild(paragraphElement);
        }


        // JavaScript to add hover effect
        var cells = document.querySelectorAll('#wordTable td');

        cells.forEach(function (cell) {
            cell.addEventListener('mouseover', function () {
                this.classList.add('main');

                // Get previous cell
                var prevCell = this.previousElementSibling;
                if (prevCell) {
                    prevCell.classList.add('hovered');
                }

                // Get next cell
                var nextCell = this.nextElementSibling;
                if (nextCell) {
                    nextCell.classList.add('hovered');
                }

                // Get cell in the same position from the previous row
                var parentRow = this.parentElement;
                var rowIndex = parentRow.rowIndex;
                var cellIndex = this.cellIndex;
                var prevRow = parentRow.previousElementSibling;
                if (prevRow) {
                    var prevRowCell = prevRow.cells[cellIndex];
                    if (prevRowCell) {
                        prevRowCell.classList.add('hovered');
                    }
                }

                // Get cell in the same position from the next row
                var nextRow = parentRow.nextElementSibling;
                if (nextRow) {
                    var nextRowCell = nextRow.cells[cellIndex];
                    if (nextRowCell) {
                        nextRowCell.classList.add('hovered');
                    }
                }
            });

            cell.addEventListener('mouseout', function () {
                this.classList.remove('main');
                var prevCell = this.previousElementSibling;
                if (prevCell) {
                    prevCell.classList.remove('hovered');
                }
                var nextCell = this.nextElementSibling;
                if (nextCell) {
                    nextCell.classList.remove('hovered');
                }
                var parentRow = this.parentElement;
                var rowIndex = parentRow.rowIndex;
                var cellIndex = this.cellIndex;
                var prevRow = parentRow.previousElementSibling;
                if (prevRow) {
                    var prevRowCell = prevRow.cells[cellIndex];
                    if (prevRowCell) {
                        prevRowCell.classList.remove('hovered');
                    }
                }
                var nextRow = parentRow.nextElementSibling;
                if (nextRow) {
                    var nextRowCell = nextRow.cells[cellIndex];
                    if (nextRowCell) {
                        nextRowCell.classList.remove('hovered');
                    }
                }
            });
        });

        //Highlighting words function
        cells.forEach(function (cell) {
            cell.addEventListener('click', function () {

                if (this.classList.contains('click')) {
                    // If it exists, remove the class
                    this.classList.remove('click');
                } else {
                    this.classList.add('click');

                }

            });
        });
